[package]
name = "dateberry"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.9", features = ["web-axum"] }
axum = { version = "0.6", features = ["headers"] }
sync_wrapper = "0.1.1"
svg = "0.13"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
chrono-tz = "0.8.1"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
icalendar = { version = "0.15", features = ["chrono-tz"] }
iso8601 = { version = "0.6", features = ["chrono", "serde"] }

[dev-dependencies]
tokio = { version = "1.22", features = ["full"] }
