[package]
name = "dateberry"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.9.0", features = ["web-axum"] }
axum = "0.6.3"
sync_wrapper = "0.1.1"
svg = "0.13.0"
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
num-traits = "0.2"

[dev-dependencies]
tokio = {version = "1.0", features = ["full"]}
